# mypy.ini
[mypy]
python_version = 3.12
# Point to your Django project's settings module
django_settings_module = ad_agency_project.settings

# Plugins for Django ORM and REST Framework
plugins = 
    mypy_django_plugin.main,
    mypy_drf_plugin.main
    #mypy_drf_plugin.main

# Strictness settings
strict = True
# You can uncomment and adjust these for more granular control if `strict = True` is too much initially
# disallow_any_unimported = True
# disallow_any_untyped_arg = True
# disallow_incomplete_defs = True
# disallow_untyped_defs = True
# no_implicit_optional = True
# warn_return_any = True
# warn_unused_configs = True
# warn_redundant_casts = True
# warn_unused_ignores = True

# Per-module options if you need to relax strictness for specific files/apps
# [mypy-ads.migrations.*]
# ignore_errors = True
# [mypy-*.apps]
# ignore_errors = True
# [mypy-*.urls]
# ignore_errors = True
# [mypy-*.admin]
# ignore_errors = True # Admins can sometimes be tricky with strictness

[mypy.plugins.django_settings]
# This tells mypy-django-plugin where to find your Django settings
# It should match the django_settings_module above
DJANGO_SETTINGS_MODULE = ad_agency_project.settings