# Generated by Django 4.2.10 on 2025-06-09 10:32

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name of the brand.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "daily_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Maximum allowed advertising spend per day for this brand.",
                        max_digits=10,
                    ),
                ),
                (
                    "monthly_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Maximum allowed advertising spend per month for this brand.",
                        max_digits=10,
                    ),
                ),
                (
                    "current_daily_spend",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Current accumulated spend for the current day.",
                        max_digits=10,
                    ),
                ),
                (
                    "current_monthly_spend",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Current accumulated spend for the current month.",
                        max_digits=10,
                    ),
                ),
                (
                    "last_daily_reset",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="The date when the daily budget was last reset.",
                    ),
                ),
                (
                    "last_monthly_reset",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="The date when the monthly budget was last reset.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brand",
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the campaign.", max_length=255),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Determines if the campaign is currently running or paused. Controlled by budget and dayparting.",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        blank=True,
                        help_text="Optional: Start time (HH:MM:SS) for the campaign to be active. Blank means always active.",
                        null=True,
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True,
                        help_text="Optional: End time (HH:MM:SS) for the campaign to be active. Blank means always active.",
                        null=True,
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="agency_ads.brand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign",
                "unique_together": {("brand", "name")},
            },
        ),
        migrations.CreateModel(
            name="AdImpression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost incurred for this single ad impression.",
                        max_digits=10,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the impression occurred.",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="impressions",
                        to="agency_ads.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ad Impression",
                "ordering": ["-timestamp"],
            },
        ),
    ]
